# Add 'root' label to any root file changes
# Quotation marks are required for the leading asterisk
root:
- changed-files:
  - any-glob-to-any-file: '*'

## Equivalent of the above mentioned configuration using another syntax
Documentation:
- changed-files:
  - any-glob-to-any-file: ['cba_configs/**', '**/*.md']
  
Repo-Update:
- changed-files:
  - any-glob-to-any-file: ['.github/**', '**/*.yml']

Mission-Update:
- changed-files:
  - any-glob-to-any-file: ['basis_uebungsplatz_2024.Enoch/*.ext', 'basis_uebungsplatz_2024.Enoch/*.sqm', 'basis_uebungsplatz_2024.Enoch/*.sqf', 'basis_uebungsplatz_2024.Enoch/*.hpp', 'basis_uebungsplatz_2024.Enoch/*.txt']

Loadout-Update:
- changed-files:
  - any-glob-to-any-file: 'basis_uebungsplatz_2024.Enoch/loadouts/**/loadout/*.sqf'

Packlisten-Update:
- changed-files:
  - any-glob-to-any-file: 'basis_uebungsplatz_2024.Enoch/loadouts/**/packliste/*.sqf'

Limakisten-Update:
- changed-files:
  - any-glob-to-any-file: 'basis_uebungsplatz_2024.Enoch/loadouts/**/lima/*.sqf'

Script-Update:
- changed-files:
  - any-glob-to-any-file: ['basis_uebungsplatz_2024.EnochR/fnc/**', 'basis_uebungsplatz_2024.Enoch/gui/**', 'basis_uebungsplatz_2024.Enoch/scripts/**', 'basis_uebungsplatz_2024.Enoch/sounds/**']

# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
 - head-branch: ['^feature', 'feature']

fix:
 - head-branch: ['^fix', 'fix']
