name: Package Mission

on:
  release:
    types: [created,edited]

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Missions
        uses: actions/checkout@v4
        with:
          path: source
      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "German-Rangers-MM/PBO-Packer"
          latest: true
          fileName: "pbo-packer"
      - name: Package Missions
        run: |
          mkdir -p pbos
          chmod +x ./pbo-packer
          ./pbo-packer ./source ./pbos
          echo "Packed missions:"
          ls -lh ./pbos/
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name || steps.get-release.outputs.tag }}
          files: |
            pbos/*.pbo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
