name: Package Mission

on:
  release:
    types: [created,edited]

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Missions
        uses: actions/checkout@v4
        with:
          path: source
      - uses: robinraju/release-downloader@v1.7
        with:
          repository: "German-Rangers-MM/PBO-Packer"
          latest: true
          fileName: "pbo-packer"
          out-file-path: "./pbo-packer"
      - name: Package Missions
        run: |
          mkdir -p pbos
          chmod +x ./pbo-packer
          ./pbo-packer ./source ./pbos
          echo "Packed missions:"
          ls -lh ./pbos/

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./pbos/*.pbo
          asset_name: ${{ github.event.repository.name }}_${{ github.event.release.tag_name }}.pbo
          asset_content_type: application/octet-stream
